### ISSUE TITLE
Вынести числа в переменные и дать говорящие имена

### ISSUE THREAD

**Issue by coursar** [dilyarakhabibullina/HomeWorkLessonNoOneBonusSportMaster#1]
https://github.com/dilyarakhabibullina/HomeWorkLessonNoOneBonusSportMaster/blob/9d9d242884e7877c2c9f095b594267ddae4a6fcf/src/Main.java#L10-L18

**Comment by dilyarakhabibullina** [comment]
Вынесла числа в переменные

**Comment by coursar** [comment]
Issue нужно закрывать сообщениями коммита
